package-lock.json, package.json, src/App.jsx, src/components/bot/ChatBox.jsx, src/components/bot/ChatHead.jsx, src/components/bot/buttons/CloseChatBtn.jsx, src/components/bot/buttons/SettingsBtn.jsx, src/components/bot/ui/Chat.jsx, src/components/bot/ui/Error.jsx, src/libs/bot-details.js, src/libs/depts.js, src/providers/InternetProvider.jsx, src/styles/globals.css, src/utils/firebase-config.js, tailwind.config.js
Add animations to chat head, new styling to components and add temporary function to handle user queries for departments.
* Manual Testing
**Test Configuration**:
* Browser: Google Chrome
* Browser version: Version 123.0.6312.123 (Official Build) (64-bit)
* Text editor: Visual Studio Code
=> chore: v1.5.0

src/components/bot/ChatBox.jsx, src/components/bot/ChatHead.jsx
Add responsiveness to chat ui #25. Add cloud bubble to chat head #23.
* Manual Testing
**Test Configuration**:
* Browser: Google Chrome
* Browser version: Version 123.0.6312.123 (Official Build) (64-bit)
* Text editor: Visual Studio Code
=> chore: v1.7.0

.github/pull_request_template.md, src/components/bot/ChatBox.jsx, src/components/bot/header/Header.jsx, src/components/bot/input/MessageInput.jsx, src/components/bot/sections/Messages.jsx, src/components/bot/sections/Settings.jsx, src/components/bot/sections/SuggestedQuestions.jsx, src/components/bot/ui/SampleBotChat.jsx, src/components/bot/ui/SampleUserChat.jsx, src/lib/bot-details.js, src/lib/greet.js
Code split the ui of chat box. Separate each sections of the chat box to its own components with corresponding props. Users can now send messages properly because of the newly added checking/validation for user messages if it has whitespaces. Lastly, update the pr template and change the checklist header to acceptance criteria.
Fixes #21 
1. Send messages
* to test if the whitespaces in the beginning or end of a message will still display
**Test Configuration**:
* Browser: Google Chrome
* Browser version: 124.0.6367.61 (Official Build) (64-bit)
* Text editor: Visual Studio Code
=> chore: v1.8.0

README.md
###
Update the readme file for documentation
###
- Related Issue(s) #36 
- Closes #
=> docs: update readme (@moonbamijam)

src/hooks/useChatbot.js
###
The bot will still display typing ui even if "something went wrong"
###
- Related Issue(s) #56 
- Closes #
=> fix: bot still typing if something went wrong (#56)

src/components/bot/settings/appearance/themes/ThemeSwitch.jsx, src/contexts/ThemesProvider.jsx, src/lib/settings/themes.js
###
Update the theme changer button for app UI consistency
###
- Related Issue(s) #45 
- Closes #
=> feat: new theme changer button (#45)

.github/labeler.yml
###
Improve labeler automation action by adding new properties and labels
###
- Closes #
=> chore: add new configurations to labeler

package.json, pnpm-lock.yaml
###
Add prettier script, add js files to lint-stage configurations and remove dotenv-cli package since it is not being used anymore
###
- Closes #
=> chore: update scripts and remove dotenv cli deps

src/components/bot/ChatBox.jsx, src/components/bot/buttons/MaximizeBtn.jsx, src/components/bot/common/Grid.jsx, src/components/bot/sections/Messages.jsx, src/components/bot/sections/SettingSwitch.jsx, src/components/bot/sections/SuggestedMessages.jsx, src/components/bot/settings/Settings.jsx, src/components/bot/settings/SettingsBtn.jsx, src/components/bot/settings/SettingsTitle.jsx, src/components/bot/settings/appearance/AppearanceSettings.jsx, src/components/bot/settings/appearance/fonts/FontFamilySwitch.jsx, src/components/bot/settings/appearance/fonts/FontSizeSwitch.jsx, src/components/bot/settings/appearance/themes/ThemeSwitch.jsx, src/components/bot/settings/nav/SettingsNavBar.jsx, src/components/bot/settings/nav/SettingsNavTitle.jsx, src/components/bot/ui/Button.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/bot/ui/Version.jsx, src/components/page/Page.jsx, src/lib/settings/settingsList.js, src/main.jsx, src/styles/custom-media-query.css, src/styles/globals.css
###
Update the responsiveness of the ui especially for small screens
###
- Related Issue(s) #46 
- Closes #
=> impr: ui responsiveness

.release-it.json
=> chore: update release-it requiredBranch

.github/labeler.yml, .release-it.json
###
Add the release-it file to labeler devops label
###
- Closes #
=> chore: add release-it json to devops label

CHANGELOG.md, package.json
###
Release v1.10.0 
###
- Closes #
=> chore: release v1.10.0

.release-it.json
###
Add build scope for release-it commit message if ever we use merge commit through pr
###
- Closes #
=> chore: add build scope to release-it commit msg

.release-it.json, package.json
###
Update release-it configurations
###
- Closes #
=> chore: update release-it configs

.gitignore, README.md, package.json, pnpm-lock.yaml, turbo.json
###
Add turbo repo for fast building time
###
- Closes #
=> chore: add turborepo

src/components/bot/header/Header.jsx, src/components/bot/input/MessageInput.jsx, src/components/bot/sections/MiniProfile.jsx, src/components/bot/settings/Settings.jsx, src/components/bot/ui/Chat.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/bot/ui/SampleBotChat.jsx, src/components/bot/ui/Typing.jsx, src/hooks/useChatbot.js, src/lib/bot/chatbot.js, src/lib/settings/settingsList.js, src/utils/greet.js
BREAKING CHANGE: new api to chatbot
###
Move api to chatbot config for file consistency and readability. Also move chatbot config to its own directory
###
- Closes #
=> refactor: move chatbot url to chatbot config

CHANGELOG.md, package.json
###
Release v2.0.0
###
- Closes #
=> chore: release v2.0.0

index.html, package.json, pnpm-lock.yaml, public/site.webmanifest, vite.config.js
###
Add PWA support using vite-pwa-plugin package
###
- Closes #
=> feat: add pwa support

turbo.json
###
For some reason, api keys can't detect in vercel dev deployments
###
- Closes #
=> fix: firebase error auth/api key not valid

package.json, pnpm-lock.yaml, src/App.jsx, src/components/bot/Chat.jsx, src/components/bot/ChatBox.jsx, src/components/bot/header/Header.jsx, src/components/bot/input/MessageInput.jsx, src/components/bot/sections/Messages.jsx, src/components/bot/sections/MiniProfile.jsx, src/components/bot/settings/Settings.jsx, src/components/bot/skeletons/ChatSkeleton.jsx, src/components/bot/ui/Button.jsx, src/components/bot/ui/Chat.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/bot/ui/ChatUI.jsx, src/components/bot/ui/Loading.jsx, src/components/bot/ui/SampleBotChat.jsx, src/components/bot/ui/Typing.jsx, src/contexts/ChatbotContext.jsx, src/hooks/useChatbot.js, src/hooks/useScrollIntoView.js, src/lib/bot/chatbotConfig.js, src/lib/settings/settingsList.js, src/providers/ChatbotProvider.jsx, src/styles/utils.css, src/utils/greet.js, src/utils/scrollInto.js
> [!NOTE]
> IN PROGRESS
###
Change the post structure of chats to improve document fetching from firebase, therefore improving performance as well. Also added infinite scrolling!
> [!NOTE]
> ### Though, there's just one caveat here:
>
> The infinite scrolling is a mock version
>   ![9-08-2024 (17-21-16)](https://github.com/user-attachments/assets/a9c67beb-564f-41c2-9306-e31092c11d27)
>
> Because I can't still find a way to **'really'** get chats this time in the conversation field like the **limit()** method by firebase for documents. Since we're **not** fetching chat by documents now.
>   ![image](https://github.com/user-attachments/assets/3f2263d1-0eb0-49b3-9eaf-9f62a9e46516)
###
- Related Issue(s) #29, #86 
- Closes #86
=> feat: add infinite scrolling to chat

src/hooks/useChatbot.js, src/lib/bot/chatbotConfig.js
> [!note]
> Fix files that exposes api url
###
Rewriting git history.
###
- Closes #
=> fix: api url exposure

.gitignore
###
Add env files wildcard to gitignore
###
- Closes #
=> chore: add env variant files to gitignore

.github/labeler.yml
###
This will fix github-actions labeler adding new **dependencies** label
###
- Closes #
=> chore: update dependecies label to packages

index.html, src/components/bot/sections/Messages.jsx, src/firebase/config.js, src/hooks/useChatbot.js, src/lib/bot/chatbotConfig.js, turbo.json
###
Improvements to some features, formatting and some fixing
###
- Closes #
=> impr: features and few fixes

CHANGELOG.md, package.json
###
Release v2.1.0
###
- Closes #
=> chore: release v2.1.0

.release-it.json
###
Change the commit message by release-it
###
- Closes #
=> chore: update release-it commit message

src/components/bot/input/MessageInput.jsx
###
Selecting using tab in chatbox causing the sreen to change vie since faqs menu is still display but with 0 opacity
###
- Closes #
=> fix: faqs menu can be selected by tab

.github/labeler.yml
###
Misspelled package label 
###
- Closes #
=> chore: fix misspelled label

src/app/Home.jsx, src/components/cards/PageCard.jsx, src/components/common/Grid.jsx, src/components/ui/Button.jsx
###
Added responsiveness to modal in landing page
###
- Closes #
=> feat: responsive modal ui

src/hooks/useChatbot.js, src/lib/bot/chatbotConfig.js
###
When send gibberish chat, something will went wrong. Fixed this by adding a fallback response for error/gibberish messages
###
- Related Issue(s) #99 
- Fixes #99
=> fix: undefined bot response

.github/workflows/cob-chatbot-cd.yml, .github/workflows/cob-chatbot-hotfix.yml, .gitignore, vercel.json
###
Added CD pipeline to vercel
###
- Closes #
=> chore: add vercel cd workflow

turbo.json
=> fix: firebase insufficient permission

.github/workflows/cob-chatbot-dev.yml, .github/workflows/cob-chatbot-hotfix.yml, .github/workflows/cob-chatbot-release.yml
=> chore: config cd

src/components/bot/sections/Messages.jsx
###
Improved the height checking in messages component
###
- Closes #
=> fix: scroll into view not working properly

.github/workflows/cob-chatbot-dev.yml, src/components/cards/PageCard.jsx
###
Whenever going to /bacoor-gov, you have to refresh in order to gain permission. So I changed the **Link** tag provided by react-router-dom and instead used normal anchor tag for full page refresh
###
- Related Issue(s) #109 
- Fixes #109
=> fix: require full refresh to gain permission

src/components/bot/sections/Messages.jsx
###
Infinite scrolling happens immediately on reload due to the overflow auto scrolling
###
- Related Issue(s) #100 
- Fixes #100
=> fix: scrolling on reload

src/utils/splitLink.js
###
Due to the change of pattern in intent, there is no other way to check this as of no. Therefore only use one type of link message all throughout
###
- Related Issue(s) #112
- Fixes #112
=> fix: splitted links are not working

.github/pull_request_template.md, src/hooks/useChatbot.js, src/utils/greet.js
###
Duplicate bug finally fixed fr. Instead of using useEffect on when to greet, we now use getConvesationHistory function to check weather the bot should greet this or not if there's already a conversation.
###
- Fixes #118
=> fix: requires full refresh for permission

src/app/CityHall.jsx, src/app/Home.jsx, src/components/bot/ChatHead.jsx, src/components/bot/settings/Settings.jsx, src/components/bot/settings/SettingsWrapper.jsx, src/components/bot/settings/about/About.jsx, src/components/bot/settings/appearance/AppearanceSettings.jsx, src/components/bot/settings/nav/SettingsNavBar.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/ui/Button.jsx, src/contexts/AuthContext.jsx, src/main.jsx, src/providers/AuthProvider.jsx, src/styles/globals.css
###
Improvements to existing features and ui
###
- Closes #
=> impr: features and ui

src/app/CityHall.jsx, src/components/bot/ChatBox.jsx, src/components/bot/ChatHead.jsx, src/components/bot/ui/ChatUI.jsx, src/contexts/ChatContext.jsx, src/main.jsx, src/providers/ChatProvider.jsx
###
Add a chat preview when bot is going to send images or videos
###
- Closes #94
=> feat: add chat preview for image and video

.gitignore, package.json, src/app/CityHall.jsx, src/components/bot/ChatBox.jsx, src/components/bot/ChatHead.jsx, src/components/bot/sections/ChatInputSection.jsx, src/components/bot/sections/ChatSection.jsx, src/components/bot/settings/appearance/themes/ThemeSwitch.jsx, src/components/bot/settings/sound/SoundSettings.jsx, src/components/bot/settings/sound/chat-sent/ChatSentSoundSwitch.jsx, src/hooks/useChatbot.js, src/hooks/useSound.js, src/providers/SoundProvider.jsx, src/utils/scrollInto.js
###
Small fixes and features
###
- Closes #
=> impr: features and fixes

index.html, src/components/bot/buttons/RadioButton.jsx, src/components/bot/common/Grid.jsx, src/components/bot/settings/appearance/fonts/FontFamilySwitch.jsx, static/settings/font_families.json
###
Fixes fonts are not applying to different devices that doesn't have that font
###
- Closes #
=> fix: fonts not applying to other device

src/components/bot/sections/ChatInputSection.jsx, src/components/bot/settings/appearance/fonts/FontSizeSwitch.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/header/Header.jsx
###
Small improvements to chatbox
###
- Closes #
=> impr: chatbox

src/components/bot/Chat.jsx, src/components/bot/ChatHead.jsx, src/components/bot/header/Header.jsx, src/components/bot/sections/MiniProfile.jsx, src/components/bot/settings/Settings.jsx, src/components/bot/settings/SettingsBtn.jsx, src/components/bot/settings/about/About.jsx, src/components/bot/settings/nav/SettingsNavBar.jsx, src/components/bot/ui/ChatPreview.jsx, src/components/bot/ui/ChatUI.jsx, src/components/bot/ui/SampleBotChat.jsx, src/components/bot/ui/Typing.jsx, src/hooks/useChatbot.js, src/lib/bot/chatbotConfig.js, src/lib/settings/settingsList.js, src/providers/ChatbotProvider.jsx, src/utils/greet.js
###
Added a dynamic bot configurations 
###
- Closes #
=> feat: add dynamic chatbot configurations

src/providers/FontProvider.jsx
###
Fixed undefined variable import in font provider
###
- Closes #
=> fix: undefined variable import

vercel.json
###
404 not found displays in the Bacoor City Hall page on hard refresh
###
- Closes #
=> fix: 404 not found on hard refresh

src/components/bot/sections/ChatSection.jsx, src/components/bot/settings/appearance/fonts/FontFamilySwitch.jsx, src/components/bot/settings/appearance/fonts/FontSizeSwitch.jsx, src/components/bot/settings/appearance/themes/ThemeSwitch.jsx, src/components/bot/settings/sound/chat-sent/ChatSentSoundSwitch.jsx, src/components/header/Header.jsx, src/hooks/useSound.js, src/providers/FontProvider.jsx, src/providers/SoundProvider.jsx, src/providers/ThemeProvider.jsx, src/utils/timestamp.js, static/settings/themes.json
###
Small performance improvements to providers and setting changer functions
###
- Closes #
=> impr: providers

src/components/header/Header.jsx, src/providers/ThemeProvider.jsx
###
System theme can be confusing in toggle theme buttons such as in the landing page header. This will fix it and can toggle between system and light/dark theme
###
- Closes #
=> fix: system theme toggler

src/app/Home.jsx
refactor: remove modal
###
Removed unnecessary modal in landing page
###
- Closes #
=> perf: new cta button to landing page

src/components/bot/icons/DevIcon.jsx, src/components/bot/sections/MiniProfile.jsx, src/components/ui/Button.jsx, src/components/ui/Image.jsx, src/lib/bot/chatbotConfig.js
###
Added small adjustments to about ui in chat settings
###
- Closes #
=> feat: new about ui

index.html
style: use original url for og image
###
###
- Closes #
=> fix: meta og image not displaying

src/components/bot/Chat.jsx, src/components/bot/sections/ChatInputSection.jsx, src/components/bot/sections/ChatSection.jsx, src/components/bot/sections/SuggestedChatSection.jsx, src/components/bot/settings/appearance/chathead/ChatHeadSwitch.jsx, src/components/bot/settings/appearance/fonts/FontFamilySwitch.jsx, src/components/bot/settings/appearance/fonts/FontSizeSwitch.jsx, src/components/bot/settings/appearance/themes/ThemeSwitch.jsx, src/components/bot/settings/sound/chat-sent/ChatSentSoundSwitch.jsx, src/components/common/ItemsRenderer.jsx
###
Added a renderer/mapping component for organized items mapping
###
- Closes #
=> perf: add renderer/mapping component

src/app/CityHall.tsx, src/components/bot/ChatBox.tsx, src/components/bot/ChatHead.tsx, src/components/bot/header/Header.tsx, src/components/bot/sections/SettingSwitch.tsx, src/components/bot/settings/appearance/chathead/ChatHeadSwitch.tsx, src/providers/ChatbotProvider.tsx
###
Can directly chat without the need of clicking the chat head only for small screens
###
- Closes #
=> feat: direct chat to mobile

src/components/bot/Chat.tsx, src/components/bot/layouts/ChatBubble.tsx, src/components/bot/layouts/ImageDimmer.tsx, src/components/bot/sections/ChatSection.tsx, src/components/bot/ui/ChatUI.tsx, src/hooks/useChatbot.ts, src/shared/file-extensions.ts, src/shared/type.ts, src/utils/extract-file-name-from-url.ts, src/utils/splitLink.ts, src/utils/splitMessage.ts
###
Adjust the styling in the preview of the files as well as getting it from the server
###
- Closes #
=> feat: handle dynamic files preview (@moonbamijam, @Jireh-sama)

src/features/chat/components/sections/ChatSection.tsx, src/features/chat/layouts/Chat.tsx, src/features/chat/layouts/ChatLayout.tsx, src/features/chat/layouts/ChatUI.tsx, src/hooks/useChatbot.ts, src/shared/file-extensions.ts, src/shared/ts/type.ts
###
Improve the ui of response when it comes to files, videos and images
###
- Closes #
=> feat: improved chat for files and links

src/components/pages/city-hall/articles/ArticleLeft.tsx, src/components/pages/city-hall/articles/ArticleRight.tsx, src/components/pages/city-hall/layouts/Section.tsx, src/components/pages/city-hall/layouts/footer/Footer.tsx, src/components/pages/city-hall/layouts/header/Dropdown.tsx, src/components/pages/city-hall/layouts/header/Header.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/chat/layouts/ChatHead.tsx, src/features/chat/layouts/header/ChatBoxHeader.tsx, src/features/settings/components/appearance/chathead/ChatHeadSwitch.tsx, src/layouts/CityHallUI.tsx
###
Replicate a portion of responsiveness from the official web page of city hall
###
- Closes #156
=> feat: responsive city hall page on small screen

.release-it.json
###
Experimentally added types to conventional changelog
###
- Closes #
=> chore: add impr type to conventional changelog types

src/contexts/ChatbotContext.tsx, src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/layouts/ChatBox.tsx, src/hooks/useChatbot.ts, src/providers/ChatbotProvider.tsx, src/shared/collection-refs.ts, src/shared/ts/type.ts, static/messages/services-and-process.json
###
Replaced faqs to list of questions about services and process
###
- Closes #
=> feat: replace faqs to static services and process questions

src/features/chat/components/ChatBubble.tsx, src/features/chat/components/sections/ChatSection.tsx, src/features/chat/layouts/Chat.tsx, src/features/chat/layouts/ChatLayout.tsx, src/utils/timestamp.ts, tailwind.config.js
###
Added a full timestamp whenever a chat is clicked
###
- Closes #
=> feat: add full timestamp to chats

README.md
=> docs: update about and features list and add others section

.gitignore
###
Add services knowledge format to gitignore since this is just for formatting services knowledge through admin
=> chore: add services knowledge format to gitignore

src/features/ratings/RatingBox.tsx
###
Increase the number of conversation as to when the rating box will show up
=> impr: when will rating box show up

src/features/chat/components/sections/ChatInputSection.tsx
###
Change the for, id and name of the user input field
=> fix: incorrect use of for in label in user input field

src/features/chat/layouts/ChatLayout.tsx, src/features/department/components/buttons/DepartmentBtn.tsx
###
Departments response ui is not clear and incoherent
=> fix: departments response ui

docs/CHANGELOG.md, package.json
=> chore: release v3.1.0

src/features/chat/components/SampleBotChat.tsx, src/features/chat/components/previews/ChatPreview.tsx, src/features/chat/components/sections/ChatSection.tsx, src/features/chat/layouts/Chat.tsx, src/features/chat/layouts/ChatLayout.tsx, src/hooks/useChatbot.ts, src/lib/process-response.ts, src/utils/extract-link.ts
###
Revert ui for responses with links to avoid conflicts in admin panel whenever an admin inputs a link. This should also be placed in frontend the way it was placed in admin
=> feat: refactor ui for responses with links

src/app/Error.tsx
###
Update the ui of the error page
=> feat: update error page ui

src/features/chat/components/ChatBubble.tsx, src/features/chat/layouts/ChatLayout.tsx
Adjust the whitespacing for the chats of both user and bot. This can handle the indentations from the bot answers
=> feat: adjust chat whitespacing

src/hooks/useChatbot.ts
###
Remove is else when the bot detected a none intent since this is already unnecessary
=> refactor: remove unnecesarry if else clause in bot reply

src/features/chat/layouts/ChatLayout.tsx
=> style: remove log to chat layout

.github/workflows/cob-chatbot-pr-preview.yml
###
Simple rename of dev workflow
=> refactor: rename dev workflow

src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/ChatSection.tsx
###
just fixing the positioning of chatbox peripherals
=> fix: scroll button and one tap questions positioning

src/features/chat/components/sections/SuggestedChatSection.tsx
fix: inconsistent width and height to suggested chats
###
Hotfixes suggested chat inconsistencies
=> fix: scroll behaviour state in suggested chats

README.md
=> docs: update contributing and add security section

src/features/chat/components/sections/SuggestedChatSection.tsx
###
improvements to suggested chat section such as ui and scrolling behavior. Also fixed the #186 even though I can't reproduce it, I am certain it happened due to overflow-clip of the parent component in suggested chat section
###
- Fixes #186
=> impr: suggested chat section ui/ux

src/components/pages/city-hall/layouts/header/Header.tsx, src/components/pages/city-hall/ui/Logo.tsx
###
simple fix to logo links in city hall page that causes to page errors
=> fix: outdated link to city hall page logos

src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/ChatSection.tsx, src/features/chat/layouts/ChatBox.tsx
###
Added a small text reminder for users that the chatbot is not going to be accurate at all times
=> feat: add chatbot response reminder to chatbox

src/app/Home.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/chat/layouts/ChatHead.tsx
###
The chatbot doesn't immediately greet on first time visits due to the Link tag provided by react router that causes the page to load immediately. This doesn't give enough time for the bot to post a chat and greet the user before the user opened the chat head. This leads us to require the users to reload first.  This is now fixed by adding some checking to the chat head if the length of the conversation is still 0, then don't show yet. Also replace the Link tag provided by react router into a default anchor.
=> fix: chatbot does not greet on slow 4 devices

src/features/chat/layouts/ChatBox.tsx
###
Bring back the chatbot reminder due to chatbox refactoring from;
- #193
=> fix: missing chatbot reminder due to chatbox refactoring

src/app/Home.tsx, src/constants/url/base-url.ts, src/main.tsx, vite.config.ts
###
Add **_/user_** baseUrl for production url consistency
=> feat: add baseUrl

.gitignore
###
Ignored all .txt files since most of it are just used for knowledge formatting
=> chore: ignore all .txt files

package.json, pnpm-lock.yaml, src/features/settings/components/Settings.tsx, src/features/settings/components/security/SecuritySection.tsx, src/features/settings/constants/settings-list.ts, src/lib/variants/skeleton-screen-variants.ts, src/styles/markdown.css, vite.config.ts
###
Added security section that uses markdown file to render content. The content from this section is based from our security docs
=> feat: add security section to about settings

src/contexts/ChatbotContext.tsx, src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/ChatSection.tsx, src/features/chat/components/sections/SuggestedChatSection.tsx, src/features/chat/layouts/ChatBox.tsx, src/hooks/useChatbot.ts, src/providers/ChatbotProvider.tsx
###
Added a state that updates whenever the bot replied. Then, it will either let the users send a chat or pause it to avoid spams.
=> feat: add spam query handler

src/contexts/ChatbotContext.tsx, src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/SuggestedChatSection.tsx, src/providers/ChatbotProvider.tsx, src/shared/collection-refs.ts, src/shared/ts/type.ts
###
Remove the static suggested queries (#196) and replace into a dynamic one that is updating real time and editable through admin.
###
- Closes #196
=> feat: add dynamic suggested queries divided into quick and menu

src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/SuggestedChatSection.tsx
###
Small update in ui/ux to suggested queries
=> feat: update suggested queries ui/ux

src/utils/extract-link.ts
###
Update the extract link utils to handle responses that has multiple links
###
- Resolves #190
=> fix: cannot handle multiple links response

src/app/Home.tsx, src/components/GradientBotName.tsx, src/layouts/BotMiniProfile.tsx, src/layouts/BotProfile.tsx
###
Added a component for gradient bot name
=> feat: add gradient bot name

src/features/chat/components/ChatBubble.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/settings/components/Settings.tsx
###
Wrong commit message, should be bot profile instead of rating box
=> feat: add selection chat and bot profile

src/features/ratings/RatingBox.tsx
###
Adjusted the styling of the bot's name
=> feat: small ui update to rating box

src/app/CityHall.tsx, src/app/Home.tsx, src/contexts/AuthContext.tsx, src/main.tsx, src/providers/AuthProvider.tsx
###
Add extra checking to routes if the user is signed in anonymously, this checking is coming from the localStorage
###
- Resolves #207
=> fix: insufficient permissions when directing to bacoor gov

src/features/settings/components/about/chatbot-team/ChatbotTeamSection.tsx
###
Add @LelouchV27 to the chatbot team
=> feat: add document manager to chatbot team sheesh

src/app/Home.tsx
###
Adjustments to height of landing page image
=> fix: landing page image overflowing to header on laptop screens

docs/SECURITY.md
###
Update the email in the security
=> docs: update security email

src/hooks/useChatbot.ts
###
Since bot typing ui waits for the query for it to actually show up. It sometimes takes time and might potentially impact ux. Small adjustments to the useChatbot hook for it to immediately show up without the need to wait for fetching
=> fix: bot typing ui takes time to show up

src/app/Home.tsx
###
Might be my final PR!!! HAHAHA
=> fix: unresponsive landing page image at small height screens

src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/SuggestedChatSection.tsx
###
Skeleton screens to suggested queries for ux improvements
=> feat: add skeleton screens to suggested queries

src/features/chat/components/sections/ChatInputSection.tsx, src/features/chat/components/sections/ChatSection.tsx, src/features/chat/components/sections/SuggestedChatSection.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/chat/layouts/header/ChatBoxHeader.tsx
###
Added a large screen toggle to chatbox
###
- Closes #209
=> feat: add large screen ui to chat box

src/contexts/ChatContext.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/chat/layouts/header/ChatBoxHeader.tsx, src/features/settings/components/Settings.tsx, src/hooks/useChatbot.ts, src/providers/ChatProvider.tsx
###
Refactor settings for optimization
=> refactor: settings state

src/contexts/ChatContext.tsx, src/features/chat/layouts/ChatBox.tsx, src/features/chat/layouts/header/ChatBoxHeader.tsx, src/features/settings/components/Settings.tsx, src/hooks/useChatbot.ts, src/providers/ChatProvider.tsx
###
Added ux improvements for desktop
=> feat: add esc key listener for closing the chat

src/features/chat/components/sections/ChatInputSection.tsx
###
Small ui update to menu queries
=> feat: update grid to menu queries

src/features/chat/layouts/ChatLayout.tsx
###
Just unmuted videos in bot reponses
=> refactor: unmute videos
